# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eea72b1b5b5a20ae97e74f6e0f521e0984097471c39c182cc768b8223ef9df823bd72d179c3fa56a40446b7702c923cd280e3abe17e0dd22efca0538e4a89580

test:
  secret_key_base: 85a434987e8be7e7140796cf4fef862785a4d7cb9d99ddb0d8fcbdceea2eab9a262ba9c11536f03f5d19c4f8dfd7ffaa139fd4b6354634f662bac1b7b4fab114

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
