QUOTES = [
    "If Not Us, Who?",
    "If Not now, when?",
    "You must do the thing you think you cannot do.",
    "The best way out is always through",
    "I can and i will",
    "You are stronger than you think",
    "Never give up",
    "Work hard dream big",
    "Hope is stronger than fear",
    "Be happy be bright be you",
    "Worry less smile more",
    "Life is a one time offer, use it well",
    "Tonight, I dream. Tomorrow I do",
    "Losers quit when they fail",
    "Winners fail until they succeed",
    "The future starts today not tomorrow",
    "Doubts kill more dreams than failure ever will",
    "Success is the sum of small efforts repeated day in day out",
    "Dreams don't work unless you do",
    "You will find strength in pain",
    "Mistakes are proof you're trying",
    "The greater your storm the brighter your rainbow",
    "Life begins at the end of your comfort zone",
    "Be you and stay you",
    "Don't just fly, Soar",
    "Never stop dreaming",
    "Dream big",
    "Only those who attempt the absurd will achieve the impossible",
    "All things are possible  believe",
    "Our thoughts determine our reality",
    "Be the change you wish to see in the world",
    "Aspire to inspire before we expire",
    "A jug fills drop by drop",
    "Difficult roads often lead to beautiful destinations",
    "Hope is the heartbeat of the soul",
    "Wherever you go, go with all your heart",
    "Pain makes people change",
    "Doubt your Doubts before you doubt yourself",
    "Nothing great ever came that easy",
    "It is possible",
    "What ever you decide to do, make sure it makes you happy",
    "Turn your wounds into wisdom",
    "Never regret anything",
    "Be the best version of you",
    "Do things everyday that scares you",
    "Never let go of your dreams",
    "We become what we think about",
    "Live what you love",
    "The best is yet to come",
    "Success is the best revenge",
    "Make a wish take a chance make a change",
    "Dream big and dare to fail",
    "You woke up, You're a miracle",
    "All you need is love",
    "What you are looking for is not out there it's in you",
    "It is better to fail aiming high than succeed aiming low",
    "Don't count the days make the days count",
    "Don't regret the pass learn from it",
    "You Only Live Once",
    "You can do anything",
    "Life doesn't get easier you just get stronger",
    "It just takes some time",
    "Stars can't shine without darkness",
    "I never lose. I either win or I learn",
    "If you do what you always did you will get what you always get",
    "Wake up with determination. go to be with satisfaction",
    "Enjoy every sandwich",
    "The obstacle is the path",
    "Every moment matters",
    "And now i'll do what's best for me",
    "Enjoy the little things",
    "We rise by lifting others",
    "Believe you can and you're halfway there",
    "Be a rainbow in someone else's cloud.",
    "Find yourself, and be that",
    "You can make a difference if you try",
    "In helping others, we help ourselves",
    "Having hope will give you courage",
    "What's done is done.",
    "If you never try you'll never know",
    "When nothing goes right...  go left",
    "Stay Strong",
    "I'm batman",
    "Life is too short to wait",
    "I will win, not immediately but definitely",
    "Enjoy every moment as it comes.",
    "Die with memories not dreams",
    "And now i'll do what's best for me",
    "Hold on, pain ends",
    "You can only do your best, and if they can't appreciate that, it's their problem.",
    "It goes on",
    "To be old and wise, you must first have to be young and stupid",
    "Don't stop until you're proud",
    "Keep moving forward",
    "Somedays you just have to create your own sunshine",
    "You are your only limit",
    "Nothing worth comes easy",
    "Make yourself a priority",
    "Life is tough, but so are you.",
    "Inhale the future, exhale the pass."
]